// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:e4c29fee-09a3-42e1-b4cf-65abeeb66502",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_523HrZxaE",
    "aws_user_pools_web_client_id": "654qp8l7onccg8s3535itjjbgs",
    "aws_appsync_graphqlEndpoint": "https://sb7pvozhrbf4rozeyrkthftg64.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "pd10s3bucket",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
